### ISSUE TITLE
Template fix

### ISSUE THREAD

**Issue by MajoAndrovic** [Kros-sk/Kros.Templates#11]
I generated new solutions with "Document" and "Documents"
- GetAllDocumentsQuery.cs contains class comment: "Get all DocumentPlural". There should be "Documents" instead of "DocumentPlural"
- DocumentsController.cs
    - method "CreateToDo" should be named "CreateDocument"
    - method GetDocument comment for response code 404 contains "Todo", there shoud be "Document"

**Comment by slashersvk** [comment]
I would like to ask you to assign me this issue.
